# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/notionink/adam/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#    vendor/notionink/adam/proprietary/proprietary/libsecril-client.so:obj/lib/libsecril-client.so

# All the blobs necessary for ADAM
PRODUCT_COPY_FILES := \
    vendor/notionink/adam/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
    vendor/notionink/adam/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
    vendor/notionink/adam/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/notionink/adam/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/notionink/adam/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/notionink/adam/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/notionink/adam/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/notionink/adam/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/notionink/adam/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/notionink/adam/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/notionink/adam/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/notionink/adam/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
    vendor/notionink/adam/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/notionink/adam/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/notionink/adam/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/notionink/adam/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/notionink/adam/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/notionink/adam/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/notionink/adam/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/notionink/adam/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/notionink/adam/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/notionink/adam/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/notionink/adam/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/notionink/adam/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/notionink/adam/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/notionink/adam/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/notionink/adam/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/notionink/adam/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/notionink/adam/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/notionink/adam/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/notionink/adam/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/notionink/adam/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/notionink/adam/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/notionink/adam/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/notionink/adam/proprietary/lib/libnvstereoutils_jni.so:system/lib/libnvstereoutils_jni.so \
    vendor/notionink/adam/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
    vendor/notionink/adam/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/notionink/adam/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/notionink/adam/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/notionink/adam/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/notionink/adam/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/notionink/adam/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/notionink/adam/proprietary/lib/omxplayer.so:system/lib/omxplayer.so \
    vendor/notionink/adam/proprietary/etc/firmware/arb_test.axf:system/etc/firmware/arb_test.axf \
    vendor/notionink/adam/proprietary/etc/firmware/load_test0.axf:system/etc/firmware/load_test0.axf \
    vendor/notionink/adam/proprietary/etc/firmware/load_test1.axf:system/etc/firmware/load_test1.axf \
    vendor/notionink/adam/proprietary/etc/firmware/load_test2.axf:system/etc/firmware/load_test2.axf \
    vendor/notionink/adam/proprietary/etc/firmware/load_test3.axf:system/etc/firmware/load_test3.axf \
    vendor/notionink/adam/proprietary/etc/firmware/load_test4.axf:system/etc/firmware/load_test4.axf \
    vendor/notionink/adam/proprietary/etc/firmware/memory_stress.axf:system/etc/firmware/memory_stress.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_os_e0000000.bin:system/etc/firmware/nvavp_os_e0000000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvavp_vid_ucode.bin:system/etc/firmware/nvavp_vid_ucode.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_h264dec2x.axf:system/etc/firmware/nvmm_h264dec2x.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_mpeg2dec.axf:system/etc/firmware/nvmm_mpeg2dec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_00001000.bin:system/etc/firmware/nvrm_avp_00001000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_0ff00000.bin:system/etc/firmware/nvrm_avp_0ff00000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_8e000000.bin:system/etc/firmware/nvrm_avp_8e000000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_9e000000.bin:system/etc/firmware/nvrm_avp_9e000000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_be000000.bin:system/etc/firmware/nvrm_avp_be000000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_e0000000.bin:system/etc/firmware/nvrm_avp_e0000000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/nvrm_avp_eff00000.bin:system/etc/firmware/nvrm_avp_eff00000.bin \
    vendor/notionink/adam/proprietary/etc/firmware/transport_stress.axf:system/etc/firmware/transport_stress.axf \
